web:
  build: .
  command: 'bash -c ''/go/src/timlink/timlink'''
  working_dir: /go/src/timlink
  environment:
    PORT: 8080
    MONGO_URL: 'mongolab:27017'
    GO_ENV: 'production'
  ports:
    - '8080:8080'
  links:
    - mongolab
mongolab:
  image: mongo

